/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';

export function Cloud({ opacity, ...props }: any) {
	const { nodes } = useGLTF('./models/cloud/model.glb') as any;
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Node.geometry}>
				<meshStandardMaterial
					envMapIntensity={2}
					transparent
					opacity={opacity}
				/>
			</mesh>
		</group>
	);
}

useGLTF.preload('./models/cloud/model.glb');
